name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      OWNER: rendau
      IMAGE: websocket
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - run: go mod download

      - run: go install github.com/swaggo/swag/cmd/swag@v1.8.4

      - run: make swdoc

      - run: make

      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $ --password-stdin

      - run: docker build -t ghcr.io/$OWNER/$IMAGE:latest .

      - run: docker push ghcr.io/$OWNER/$IMAGE:latest
