name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      OWNER: rendau
      IMAGE: websocket
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Docker login
        run: |
          echo ${{ secrets.CR_PAT }} | docker login -u $OWNER --password-stdin ghcr.io

      - name: Docker build
        run: |
          docker build -t ghcr.io/$OWNER/$IMAGE:latest .

      - name: Docker push
        run: |
          docker push ghcr.io/$OWNER/$IMAGE:latest
